name: Code Quality Checks

on:
  workflow_call:

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - name: Clean up potential remnants of past jobs
        uses: AutoModality/action-clean@v1.1.0
      - name: Checkout out repository
        uses: actions/checkout@v4
      - name: Setup up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.12'
      - name: Analysing the code with black
        shell: bash
        run: |
          python -m pip install black
          black src --check --verbose --diff --color --line-length 120
          black test --check --verbose --diff --color --line-length 120
  mypy:
    runs-on: ubuntu-latest
    container:
      image: josafatburmeister/tree_species_seg:latest
      volumes:
        - ${{ github.workspace }}:/github/workspace
    steps:
      - name: Clean up potential remnants of past jobs
        uses: AutoModality/action-clean@v1.1.0
      - name: Checkout out repository
        uses: actions/checkout@v4
      - name: Analysing the code with mypy
        shell: bash
        run: |
          cd /github/workspace/
          python -m pip install -v --upgrade -e .'[dev]'
          mypy . --warn-unused-ignores --show-error-codes --no-incremental
  pylint:
    runs-on: ubuntu-latest
    container:
      image: josafatburmeister/tree_species_seg:latest
      volumes:
        - ${{ github.workspace }}:/github/workspace
    steps:
      - name: Clean up potential remnants of past jobs
        uses: AutoModality/action-clean@v1.1.0
      - name: Checkout out repository
        uses: actions/checkout@v4
      - name: Analysing the code with pylint
        shell: bash
        run: |
          cd /github/workspace/
          python -m pip install -v --upgrade .'[dev]'
          pylint src --rcfile=.rcfile
